server:
  port: 90

spring:
  application:
    name: cloudalibaba-comsumer-nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

service-url:
  provider-nacos: http://cloudalibaba-provider-nacos

management:
  endpoints:
    web:
      exposure:
        include: "*"