server:
  port: 8802

spring:
  application:
    name: cloud-stream-comsumer
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring.rabbit:
              host: 127.0.0.1
              port: 5672
              username: guest
              password: guest
      bindings:
        input:
          destination: testExchange
          content-type: application/json
          binder: defaultRabbit
          group: ${spring.application.name}

eureka:
  instance:
    instance-id: cloud-stream-comsumer8802
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka