server:
  port: 8001

spring:
  application:
    name: cloud-provider-payment
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1
    web:
      client:
        enabled: true
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db2019?useUnicode=True&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 486597

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entities
  configuration:
    map-underscore-to-camel-case: true

eureka:
  instance:
    instance-id: cloud-provider-payment8001
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
