server:
  port: 8002

spring:
  application:
    name: cloud-provider-payment
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db2019?useUnicode=True&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 486597

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entities
  configuration:
    map-underscore-to-camel-case: true

eureka:
  instance:
    instance-id: cloud-provider-payment8002
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
