server:
  port: 9527

spring:
  application:
    name: cloud-gateway-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cloud-provider-payment8001-get
#          uri: http://localhost:8001
          uri: lb://cloud-provider-payment
          predicates:
            - Path=/payment/get/**

        - id: cloud-provider-payment8001-lb
#          uri: http://localhost:8001
          uri: lb://cloud-provider-payment
          predicates:
            - Path=/payment/lb

eureka:
  instance:
    instance-id: cloud-gateway-gateway9527
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
