server:
  port: 8003

spring:
  application:
    name: cloud-providerzk-payment
  cloud:
    zookeeper:
      connect-string: 192.168.40.128:2181
      max-sleep-ms: 2000
      base-sleep-time-ms: 1000
